### ISSUE TITLE
Not working in MAUI app

### ISSUE THREAD

**Issue by tibitoth** [nagybalint001/typed-localization#3]
> Microsoft.Maui.Controls.Xaml.XamlParseException: 'No embeddedresource found for TypedLocalization.Samples.Maui.App'

![image](https://user-images.githubusercontent.com/8333960/187200173-2627ef39-15b5-44f9-a89c-f91f47b75f2c.png)

Repro: 
1. Create new MAUI project (runs fine)
2. Add TypedLocalization latest NuGet package (run fails)

repro: https://github.com/tibitoth/typed-localization

**Comment by nagybalint001** [comment]
I think this caused the error: https://github.com/nagybalint001/typed-localization/pull/4/commits/e1121fd3e20691728328f273c230e1585efd8611

**Comment by tibitoth** [comment]
Still not working in Android release mode because of some AOT related errors. I didn't investigate further.

**Comment by tibitoth** [comment]
@balazs-adam Is this still relevant?

**Comment by balazs-adam** [comment]
No, I think we're good as is.
